version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: ci

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: build
    ignore:
      - dependency-name: "org.junit.jupiter:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.junit.platform:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.junit.vintage:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.codehaus.plexus:plexus-utils"
        update-types: ["version-update:semver-major"]
