kotlin.stdlib.default.dependency=false
org.gradle.jvmargs=-Xmx3g
org.gradle.caching=true
org.gradle.parallel=true
org.jetbrains.intellij.platform.useCacheRedirector=false
systemProp.org.gradle.internal.http.connectionTimeout=30000
systemProp.org.gradle.internal.http.socketTimeout=120000

affected.idea.version=2026.1.4
affected.studio.version=2026.1.3.8
affected.mcp.version=261.26222.30
