subprojects {
    apply plugin: 'java-library'

    repositories { mavenCentral() }

    dependencies {
        testImplementation platform('org.junit:junit-bom:5.14.3')
        testImplementation 'org.junit.jupiter:junit-jupiter'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }

    tasks.withType(Test).configureEach { useJUnitPlatform() }

    sourceSets.configureEach { sourceSet ->
        tasks.register("audit${sourceSet.name.capitalize()}")
    }
}
